### PR TITLE
Issue 53 - Don't unnest query subparameters

### LINKED ISSUE #53: Simple Parser unnests `dimensions` and `measures` in `query` fields
For [query](https://docs.looker.com/reference/explore-params/query) fields, the dimensions and measures keys are special - they are kept in plural form, with a list as the value.

When the simple parser parses this field, it sees that it's a pluralized key, and unnests them. Example:
```
In [98]: lkml.dump(
    ...:   {
    ...:     "explores": [
    ...:       {
    ...:         "name": "queried_explore",
    ...:         "queries": [
    ...:           {
    ...:             "dimensions": ["first_dim"],
    ...:             "measures": ["first_meas"],
    ...:             "pivots": ["first_pivot"],
    ...:             "name": "aquery"
    ...:           }
    ...:         ]
    ...:       }
    ...:     ]
    ...:   }
    ...: )
Out[98]: 'explore: queried_explore {\n  query: aquery {\n    dimension: first_dim\n    measure: first_meas\n    pivots: [first_pivot]\n  }\n}'
```

### PR DESCRIPTION
**Pull request by fbertsch**
Closes #53 .

### CODE REVIEW

**Comment by joshtemple** [comment]
Thanks @fbertsch! Seems like there was an issue with CI not triggering for this PR. I've fixed it on `master`, do you mind rebasing this branch off the latest version of `master` and force-pushing to update this PR?

**Comment by joshtemple** [comment]
Sorry, looks like I also needed to toggle a setting in Circle so it runs on forks. I'm not entirely sure how to re-trigger... do you mind closing this PR and opening a new one?

**Comment by fbertsch** [comment]
@joshtemple looks like we're good to go now!

**Comment by joshtemple** [comment]
LGTM! Thanks again @fbertsch for the bugfix and for your patience with Circle.

**Pull request merged**
