### PR TITLE
Extra handling for special case where leading minus symbol with space...

### PR DESCRIPTION
**Pull request by iuriifavi**
…s in database relations

### CODE REVIEW

**Comment by joshtemple** [comment]
What problem is this PR fixing? Can you add an example of the error that happens that you're trying to fix with this?

**Comment by iuriifavi** [comment]
this is valid lkml but it would not pass because - recognized as literal 
explore: accounting_invoice {
  label: "Invoices"
  fields: [ALL_FIELDS*,
    - companies.ref*]
}

**Comment by joshtemple** [comment]
Interesting, I've never seen a dash used like this in LookML. Maybe it's an artifact of the YAML days of old LookML?

I believe we can just skip over the `-` characters. They can be ignored by the parser, since it's going to use the `,` token to separate the elements in the list. I would rather add `-` to the list of characters skipped over in the while loop [here](https://github.com/joshtemple/lkml/blob/master/lkml/lexer.py#L63) than add more if/else logic to `scan_literal`. Can you see if that change works for this case?

Please also add a unit test to `tests/test_lexer.py` to test this case. Then I'd be happy to accept this!

**Comment by iuriifavi** [comment]
I'll later today )

**Comment by joshtemple** [comment]
@iuriifavi, are you still planning to make these changes?

**Comment by joshtemple** [comment]
I'm closing this pull request for now because of inactivity.

@iuriifavi, we can always reopen it if you'd like to make these changes at some point. Thanks!

**Pull request closed without merging**
